import type { Language } from "./types";

export interface MandiMarket {
  id: string;
  name: string;
  nameHi: string;
  nameMr: string;
  district: string;
  districtHi: string;
  districtMr: string;
  lat: number;
  lng: number;
  distanceFromPuneKm: number;
  prices: {
    [cropId: string]: {
      headlinePrice: number; // ₹/kg
      minPrice: number;
      maxPrice: number;
      arrivalsTonnes: number;
      netEstimatedPrice: number; // calculated net take home
    };
  };
  congestionLevel: "Low" | "Medium" | "High";
  verifiedDate: string;
}

export const MOCK_MANDIS: MandiMarket[] = [
  // ─── Konkan / Mumbai Metropolitan ───
  {
    id: "mumbai-vashi",
    name: "Mumbai Vashi APMC",
    nameHi: "मुंबई वाशी एपीएमसी",
    nameMr: "मुंबई वाशी एपीएमसी",
    district: "Navi Mumbai",
    districtHi: "नवी मुंबई",
    districtMr: "नवी मुंबई",
    lat: 19.0748,
    lng: 72.9978,
    distanceFromPuneKm: 145,
    congestionLevel: "Medium",
    verifiedDate: "Today, 08:30 AM",
    prices: {
      Tomatoes: { headlinePrice: 34.0, minPrice: 30, maxPrice: 38, arrivalsTonnes: 120, netEstimatedPrice: 28.5 },
      Onions: { headlinePrice: 28.0, minPrice: 24, maxPrice: 31, arrivalsTonnes: 250, netEstimatedPrice: 24.7 },
      Potatoes: { headlinePrice: 22.0, minPrice: 19, maxPrice: 25, arrivalsTonnes: 180, netEstimatedPrice: 18.2 },
      Soybeans: { headlinePrice: 48.0, minPrice: 44, maxPrice: 52, arrivalsTonnes: 90, netEstimatedPrice: 43.1 },
      Wheat: { headlinePrice: 26.0, minPrice: 23, maxPrice: 28, arrivalsTonnes: 300, netEstimatedPrice: 22.4 },
      Cotton: { headlinePrice: 62.0, minPrice: 58, maxPrice: 66, arrivalsTonnes: 70, netEstimatedPrice: 56.5 },
    },
  },
  {
    id: "thane-mandi",
    name: "Thane APMC Market",
    nameHi: "ठाणे एपीएमसी बाजार",
    nameMr: "ठाणे एपीएमसी बाजार",
    district: "Thane",
    districtHi: "ठाणे",
    districtMr: "ठाणे",
    lat: 19.2183,
    lng: 72.9781,
    distanceFromPuneKm: 150,
    congestionLevel: "High",
    verifiedDate: "Today, 08:00 AM",
    prices: {
      Tomatoes: { headlinePrice: 33.0, minPrice: 29, maxPrice: 36, arrivalsTonnes: 90, netEstimatedPrice: 27.2 },
      Onions: { headlinePrice: 27.0, minPrice: 23, maxPrice: 30, arrivalsTonnes: 180, netEstimatedPrice: 23.4 },
      Potatoes: { headlinePrice: 21.5, minPrice: 18, maxPrice: 24, arrivalsTonnes: 140, netEstimatedPrice: 17.6 },
      Soybeans: { headlinePrice: 47.0, minPrice: 43, maxPrice: 50, arrivalsTonnes: 70, netEstimatedPrice: 42.0 },
      Wheat: { headlinePrice: 25.5, minPrice: 22, maxPrice: 27, arrivalsTonnes: 220, netEstimatedPrice: 21.8 },
      Cotton: { headlinePrice: 61.0, minPrice: 57, maxPrice: 64, arrivalsTonnes: 55, netEstimatedPrice: 55.2 },
    },
  },
  {
    id: "kalyan-mandi",
    name: "Kalyan APMC Market",
    nameHi: "कल्याण एपीएमसी बाजार",
    nameMr: "कल्याण एपीएमसी बाजार",
    district: "Thane",
    districtHi: "ठाणे",
    districtMr: "ठाणे",
    lat: 19.2437,
    lng: 73.1355,
    distanceFromPuneKm: 160,
    congestionLevel: "Medium",
    verifiedDate: "Today, 07:50 AM",
    prices: {
      Tomatoes: { headlinePrice: 32.0, minPrice: 28, maxPrice: 35, arrivalsTonnes: 75, netEstimatedPrice: 26.4 },
      Onions: { headlinePrice: 26.5, minPrice: 22, maxPrice: 29, arrivalsTonnes: 160, netEstimatedPrice: 22.9 },
      Potatoes: { headlinePrice: 21.0, minPrice: 18, maxPrice: 23, arrivalsTonnes: 120, netEstimatedPrice: 17.2 },
      Soybeans: { headlinePrice: 46.5, minPrice: 42, maxPrice: 49, arrivalsTonnes: 60, netEstimatedPrice: 41.5 },
      Wheat: { headlinePrice: 25.0, minPrice: 22, maxPrice: 27, arrivalsTonnes: 190, netEstimatedPrice: 21.3 },
      Cotton: { headlinePrice: 60.5, minPrice: 56, maxPrice: 63, arrivalsTonnes: 45, netEstimatedPrice: 54.6 },
    },
  },
  {
    id: "alibaug-mandi",
    name: "Alibaug APMC Market",
    nameHi: "अलिबाग एपीएमसी बाजार",
    nameMr: "अलिबाग एपीएमसी बाजार",
    district: "Raigad",
    districtHi: "रायगढ़",
    districtMr: "रायगड",
    lat: 18.6414,
    lng: 72.8722,
    distanceFromPuneKm: 140,
    congestionLevel: "Low",
    verifiedDate: "Today, 07:30 AM",
    prices: {
      Tomatoes: { headlinePrice: 30.0, minPrice: 26, maxPrice: 33, arrivalsTonnes: 40, netEstimatedPrice: 24.8 },
      Onions: { headlinePrice: 25.0, minPrice: 21, maxPrice: 27, arrivalsTonnes: 85, netEstimatedPrice: 21.6 },
      Potatoes: { headlinePrice: 20.0, minPrice: 17, maxPrice: 22, arrivalsTonnes: 65, netEstimatedPrice: 16.4 },
      Soybeans: { headlinePrice: 45.5, minPrice: 41, maxPrice: 48, arrivalsTonnes: 35, netEstimatedPrice: 40.8 },
      Wheat: { headlinePrice: 24.5, minPrice: 21, maxPrice: 26, arrivalsTonnes: 95, netEstimatedPrice: 20.9 },
      Cotton: { headlinePrice: 59.0, minPrice: 55, maxPrice: 62, arrivalsTonnes: 25, netEstimatedPrice: 53.2 },
    },
  },

  // ─── Pune Division ───
  {
    id: "pune-gultekdi",
    name: "Pune Gultekdi Market Yard",
    nameHi: "पुणे गुलटेकड़ी मार्केट यार्ड",
    nameMr: "पुणे गुलटेकडी मार्केट यार्ड",
    district: "Pune",
    districtHi: "पुणे",
    districtMr: "पुणे",
    lat: 18.4962,
    lng: 73.8647,
    distanceFromPuneKm: 18,
    congestionLevel: "High",
    verifiedDate: "Today, 09:15 AM",
    prices: {
      Tomatoes: { headlinePrice: 32.0, minPrice: 28, maxPrice: 35, arrivalsTonnes: 95, netEstimatedPrice: 26.8 },
      Onions: { headlinePrice: 25.0, minPrice: 21, maxPrice: 28, arrivalsTonnes: 190, netEstimatedPrice: 21.5 },
      Potatoes: { headlinePrice: 20.0, minPrice: 17, maxPrice: 22, arrivalsTonnes: 140, netEstimatedPrice: 16.9 },
      Soybeans: { headlinePrice: 46.0, minPrice: 42, maxPrice: 49, arrivalsTonnes: 60, netEstimatedPrice: 41.2 },
      Wheat: { headlinePrice: 24.5, minPrice: 22, maxPrice: 26, arrivalsTonnes: 210, netEstimatedPrice: 21.1 },
      Cotton: { headlinePrice: 59.0, minPrice: 55, maxPrice: 63, arrivalsTonnes: 40, netEstimatedPrice: 54.0 },
    },
  },
  {
    id: "chakan-submarket",
    name: "Chakan Sub-Market Mandi",
    nameHi: "चाकण उप-बाजार मंडी",
    nameMr: "चाकण उप-बाजार मंडी",
    district: "Pune Outer",
    districtHi: "पुणे बाहरी",
    districtMr: "पुणे बाह्य",
    lat: 18.7606,
    lng: 73.8606,
    distanceFromPuneKm: 32,
    congestionLevel: "Low",
    verifiedDate: "Today, 08:00 AM",
    prices: {
      Tomatoes: { headlinePrice: 31.0, minPrice: 27, maxPrice: 33, arrivalsTonnes: 45, netEstimatedPrice: 27.1 },
      Onions: { headlinePrice: 24.5, minPrice: 20, maxPrice: 27, arrivalsTonnes: 120, netEstimatedPrice: 21.8 },
      Potatoes: { headlinePrice: 19.5, minPrice: 16, maxPrice: 21, arrivalsTonnes: 80, netEstimatedPrice: 17.2 },
      Soybeans: { headlinePrice: 45.0, minPrice: 41, maxPrice: 48, arrivalsTonnes: 40, netEstimatedPrice: 41.5 },
      Wheat: { headlinePrice: 24.0, minPrice: 21, maxPrice: 25, arrivalsTonnes: 130, netEstimatedPrice: 21.3 },
      Cotton: { headlinePrice: 58.0, minPrice: 54, maxPrice: 61, arrivalsTonnes: 25, netEstimatedPrice: 53.2 },
    },
  },
  {
    id: "baramati-mandi",
    name: "Baramati APMC Market",
    nameHi: "बारामती एपीएमसी बाजार",
    nameMr: "बारामती एपीएमसी बाजार",
    district: "Pune",
    districtHi: "पुणे",
    districtMr: "पुणे",
    lat: 18.1514,
    lng: 74.5815,
    distanceFromPuneKm: 100,
    congestionLevel: "Low",
    verifiedDate: "Today, 07:40 AM",
    prices: {
      Tomatoes: { headlinePrice: 29.5, minPrice: 25, maxPrice: 32, arrivalsTonnes: 55, netEstimatedPrice: 24.2 },
      Onions: { headlinePrice: 23.5, minPrice: 19, maxPrice: 26, arrivalsTonnes: 100, netEstimatedPrice: 20.4 },
      Potatoes: { headlinePrice: 18.5, minPrice: 15, maxPrice: 20, arrivalsTonnes: 75, netEstimatedPrice: 15.6 },
      Soybeans: { headlinePrice: 47.0, minPrice: 43, maxPrice: 50, arrivalsTonnes: 85, netEstimatedPrice: 42.1 },
      Wheat: { headlinePrice: 24.5, minPrice: 22, maxPrice: 26, arrivalsTonnes: 160, netEstimatedPrice: 21.5 },
      Cotton: { headlinePrice: 60.0, minPrice: 56, maxPrice: 63, arrivalsTonnes: 50, netEstimatedPrice: 54.8 },
    },
  },
  {
    id: "daund-mandi",
    name: "Daund APMC Market",
    nameHi: "दौंड एपीएमसी बाजार",
    nameMr: "दौंड एपीएमसी बाजार",
    district: "Pune",
    districtHi: "पुणे",
    districtMr: "पुणे",
    lat: 18.4655,
    lng: 74.5848,
    distanceFromPuneKm: 80,
    congestionLevel: "Low",
    verifiedDate: "Today, 07:20 AM",
    prices: {
      Tomatoes: { headlinePrice: 28.5, minPrice: 24, maxPrice: 31, arrivalsTonnes: 50, netEstimatedPrice: 23.6 },
      Onions: { headlinePrice: 23.0, minPrice: 19, maxPrice: 25, arrivalsTonnes: 95, netEstimatedPrice: 20.0 },
      Potatoes: { headlinePrice: 18.0, minPrice: 15, maxPrice: 20, arrivalsTonnes: 70, netEstimatedPrice: 15.2 },
      Soybeans: { headlinePrice: 46.5, minPrice: 42, maxPrice: 49, arrivalsTonnes: 80, netEstimatedPrice: 41.6 },
      Wheat: { headlinePrice: 24.0, minPrice: 21, maxPrice: 25, arrivalsTonnes: 150, netEstimatedPrice: 21.0 },
      Cotton: { headlinePrice: 59.5, minPrice: 55, maxPrice: 62, arrivalsTonnes: 45, netEstimatedPrice: 54.2 },
    },
  },
  {
    id: "satara-mandi",
    name: "Satara Fruit & Veg Mandi",
    nameHi: "सतारा फल एवं सब्जी मंडी",
    nameMr: "सातारा फळ व भाजी मंडी",
    district: "Satara",
    districtHi: "सतारा",
    districtMr: "सातारा",
    lat: 17.6805,
    lng: 74.0183,
    distanceFromPuneKm: 110,
    congestionLevel: "Low",
    verifiedDate: "Today, 08:15 AM",
    prices: {
      Tomatoes: { headlinePrice: 30.5, minPrice: 26, maxPrice: 33, arrivalsTonnes: 60, netEstimatedPrice: 25.4 },
      Onions: { headlinePrice: 24.0, minPrice: 20, maxPrice: 26, arrivalsTonnes: 90, netEstimatedPrice: 20.2 },
      Potatoes: { headlinePrice: 19.0, minPrice: 16, maxPrice: 21, arrivalsTonnes: 70, netEstimatedPrice: 15.8 },
      Soybeans: { headlinePrice: 46.5, minPrice: 42, maxPrice: 49, arrivalsTonnes: 50, netEstimatedPrice: 41.0 },
      Wheat: { headlinePrice: 24.0, minPrice: 21, maxPrice: 26, arrivalsTonnes: 110, netEstimatedPrice: 20.2 },
      Cotton: { headlinePrice: 58.5, minPrice: 54, maxPrice: 61, arrivalsTonnes: 30, netEstimatedPrice: 52.0 },
    },
  },
  {
    id: "karad-mandi",
    name: "Karad APMC Market",
    nameHi: "कराड एपीएमसी बाजार",
    nameMr: "कराड एपीएमसी बाजार",
    district: "Satara",
    districtHi: "सतारा",
    districtMr: "सातारा",
    lat: 17.2896,
    lng: 74.1803,
    distanceFromPuneKm: 150,
    congestionLevel: "Low",
    verifiedDate: "Today, 07:10 AM",
    prices: {
      Tomatoes: { headlinePrice: 29.0, minPrice: 25, maxPrice: 32, arrivalsTonnes: 45, netEstimatedPrice: 23.8 },
      Onions: { headlinePrice: 23.5, minPrice: 19, maxPrice: 26, arrivalsTonnes: 80, netEstimatedPrice: 20.1 },
      Potatoes: { headlinePrice: 18.5, minPrice: 15, maxPrice: 20, arrivalsTonnes: 60, netEstimatedPrice: 15.4 },
      Soybeans: { headlinePrice: 47.5, minPrice: 43, maxPrice: 50, arrivalsTonnes: 70, netEstimatedPrice: 42.3 },
      Wheat: { headlinePrice: 23.5, minPrice: 21, maxPrice: 25, arrivalsTonnes: 120, netEstimatedPrice: 20.5 },
      Cotton: { headlinePrice: 58.0, minPrice: 54, maxPrice: 61, arrivalsTonnes: 35, netEstimatedPrice: 52.4 },
    },
  },
  {
    id: "sangli-mandi",
    name: "Sangli APMC Market",
    nameHi: "सांगली एपीएमसी बाजार",
    nameMr: "सांगली एपीएमसी बाजार",
    district: "Sangli",
    districtHi: "सांगली",
    districtMr: "सांगली",
    lat: 16.8524,
    lng: 74.5815,
    distanceFromPuneKm: 230,
    congestionLevel: "Medium",
    verifiedDate: "Today, 07:00 AM",
    prices: {
      Tomatoes: { headlinePrice: 28.0, minPrice: 24, maxPrice: 31, arrivalsTonnes: 70, netEstimatedPrice: 22.6 },
      Onions: { headlinePrice: 26.0, minPrice: 22, maxPrice: 29, arrivalsTonnes: 200, netEstimatedPrice: 22.1 },
      Potatoes: { headlinePrice: 18.0, minPrice: 15, maxPrice: 20, arrivalsTonnes: 85, netEstimatedPrice: 14.8 },
      Soybeans: { headlinePrice: 48.0, minPrice: 44, maxPrice: 52, arrivalsTonnes: 130, netEstimatedPrice: 42.8 },
      Wheat: { headlinePrice: 24.5, minPrice: 22, maxPrice: 26, arrivalsTonnes: 170, netEstimatedPrice: 21.0 },
      Cotton: { headlinePrice: 61.5, minPrice: 57, maxPrice: 65, arrivalsTonnes: 95, netEstimatedPrice: 55.0 },
    },
  },
  {
    id: "kolhapur-mandi",
    name: "Kolhapur APMC Market",
    nameHi: "कोल्हापुर एपीएमसी बाजार",
    nameMr: "कोल्हापूर एपीएमसी बाजार",
    district: "Kolhapur",
    districtHi: "कोल्हापुर",
    districtMr: "कोल्हापूर",
    lat: 16.7050,
    lng: 74.2433,
    distanceFromPuneKm: 240,
    congestionLevel: "Medium",
    verifiedDate: "Today, 06:50 AM",
    prices: {
      Tomatoes: { headlinePrice: 27.5, minPrice: 23, maxPrice: 30, arrivalsTonnes: 65, netEstimatedPrice: 22.1 },
      Onions: { headlinePrice: 25.5, minPrice: 21, maxPrice: 28, arrivalsTonnes: 180, netEstimatedPrice: 21.4 },
      Potatoes: { headlinePrice: 17.5, minPrice: 14, maxPrice: 19, arrivalsTonnes: 80, netEstimatedPrice: 14.2 },
      Soybeans: { headlinePrice: 47.5, minPrice: 43, maxPrice: 51, arrivalsTonnes: 120, netEstimatedPrice: 42.3 },
      Wheat: { headlinePrice: 24.0, minPrice: 21, maxPrice: 26, arrivalsTonnes: 160, netEstimatedPrice: 20.6 },
      Cotton: { headlinePrice: 60.5, minPrice: 56, maxPrice: 64, arrivalsTonnes: 80, netEstimatedPrice: 54.0 },
    },
  },
  {
    id: "solapur-apmc",
    name: "Solapur APMC Market",
    nameHi: "सोलापुर एपीएमसी बाजार",
    nameMr: "सोलापूर एपीएमसी बाजार",
    district: "Solapur",
    districtHi: "सोलापुर",
    districtMr: "सोलापूर",
    lat: 17.6599,
    lng: 75.9064,
    distanceFromPuneKm: 245,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:30 AM",
    prices: {
      Tomatoes: { headlinePrice: 29.0, minPrice: 25, maxPrice: 32, arrivalsTonnes: 80, netEstimatedPrice: 22.4 },
      Onions: { headlinePrice: 27.5, minPrice: 23, maxPrice: 30, arrivalsTonnes: 320, netEstimatedPrice: 21.9 },
      Potatoes: { headlinePrice: 18.5, minPrice: 15, maxPrice: 20, arrivalsTonnes: 90, netEstimatedPrice: 14.1 },
      Soybeans: { headlinePrice: 49.0, minPrice: 45, maxPrice: 53, arrivalsTonnes: 150, netEstimatedPrice: 42.6 },
      Wheat: { headlinePrice: 25.5, minPrice: 23, maxPrice: 27, arrivalsTonnes: 190, netEstimatedPrice: 20.8 },
      Cotton: { headlinePrice: 63.5, minPrice: 59, maxPrice: 67, arrivalsTonnes: 110, netEstimatedPrice: 55.1 },
    },
  },

  // ─── Nashik Division ───
  {
    id: "nashik-mandi",
    name: "Nashik APMC Mandi",
    nameHi: "नासिक एपीएमसी मंडी",
    nameMr: "नाशिक एपीएमसी मंडी",
    district: "Nashik",
    districtHi: "नासिक",
    districtMr: "नाशिक",
    lat: 19.9975,
    lng: 73.7898,
    distanceFromPuneKm: 210,
    congestionLevel: "Low",
    verifiedDate: "Today, 07:45 AM",
    prices: {
      Tomatoes: { headlinePrice: 36.0, minPrice: 32, maxPrice: 40, arrivalsTonnes: 210, netEstimatedPrice: 25.2 },
      Onions: { headlinePrice: 29.0, minPrice: 26, maxPrice: 32, arrivalsTonnes: 480, netEstimatedPrice: 24.8 },
      Potatoes: { headlinePrice: 21.0, minPrice: 18, maxPrice: 23, arrivalsTonnes: 160, netEstimatedPrice: 16.5 },
      Soybeans: { headlinePrice: 47.5, minPrice: 43, maxPrice: 50, arrivalsTonnes: 110, netEstimatedPrice: 41.8 },
      Wheat: { headlinePrice: 25.0, minPrice: 22, maxPrice: 27, arrivalsTonnes: 250, netEstimatedPrice: 20.9 },
      Cotton: { headlinePrice: 61.0, minPrice: 57, maxPrice: 64, arrivalsTonnes: 85, netEstimatedPrice: 53.4 },
    },
  },
  {
    id: "lasalgaon-mandi",
    name: "Lasalgaon APMC (Onion Hub)",
    nameHi: "लासलगांव एपीएमसी (प्याज केंद्र)",
    nameMr: "लासलगाव एपीएमसी (कांदा केंद्र)",
    district: "Nashik",
    districtHi: "नासिक",
    districtMr: "नाशिक",
    lat: 20.1486,
    lng: 74.2370,
    distanceFromPuneKm: 240,
    congestionLevel: "High",
    verifiedDate: "Today, 07:00 AM",
    prices: {
      Tomatoes: { headlinePrice: 34.0, minPrice: 30, maxPrice: 38, arrivalsTonnes: 80, netEstimatedPrice: 24.0 },
      Onions: { headlinePrice: 31.0, minPrice: 27, maxPrice: 34, arrivalsTonnes: 650, netEstimatedPrice: 26.5 },
      Potatoes: { headlinePrice: 20.0, minPrice: 17, maxPrice: 22, arrivalsTonnes: 120, netEstimatedPrice: 15.8 },
      Soybeans: { headlinePrice: 46.5, minPrice: 42, maxPrice: 49, arrivalsTonnes: 90, netEstimatedPrice: 41.0 },
      Wheat: { headlinePrice: 24.5, minPrice: 22, maxPrice: 26, arrivalsTonnes: 200, netEstimatedPrice: 20.5 },
      Cotton: { headlinePrice: 60.0, minPrice: 56, maxPrice: 63, arrivalsTonnes: 70, netEstimatedPrice: 52.8 },
    },
  },
  {
    id: "malegaon-mandi",
    name: "Malegaon APMC Market",
    nameHi: "मालेगांव एपीएमसी बाजार",
    nameMr: "मालेगाव एपीएमसी बाजार",
    district: "Nashik",
    districtHi: "नासिक",
    districtMr: "नाशिक",
    lat: 20.5579,
    lng: 74.5287,
    distanceFromPuneKm: 280,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:45 AM",
    prices: {
      Tomatoes: { headlinePrice: 33.0, minPrice: 29, maxPrice: 36, arrivalsTonnes: 60, netEstimatedPrice: 23.4 },
      Onions: { headlinePrice: 28.5, minPrice: 24, maxPrice: 31, arrivalsTonnes: 280, netEstimatedPrice: 24.0 },
      Potatoes: { headlinePrice: 19.5, minPrice: 16, maxPrice: 22, arrivalsTonnes: 95, netEstimatedPrice: 15.4 },
      Soybeans: { headlinePrice: 46.0, minPrice: 42, maxPrice: 49, arrivalsTonnes: 75, netEstimatedPrice: 40.6 },
      Wheat: { headlinePrice: 24.0, minPrice: 21, maxPrice: 26, arrivalsTonnes: 170, netEstimatedPrice: 20.1 },
      Cotton: { headlinePrice: 59.5, minPrice: 55, maxPrice: 62, arrivalsTonnes: 60, netEstimatedPrice: 52.4 },
    },
  },

  // ─── Aurangabad / Marathwada Division ───
  {
    id: "aurangabad-mandi",
    name: "Chhatrapati Sambhajinagar APMC",
    nameHi: "छत्रपति संभाजीनगर एपीएमसी",
    nameMr: "छत्रपती संभाजीनगर एपीएमसी",
    district: "Aurangabad",
    districtHi: "औरंगाबाद",
    districtMr: "औरंगाबाद",
    lat: 19.8762,
    lng: 75.3433,
    distanceFromPuneKm: 235,
    congestionLevel: "Medium",
    verifiedDate: "Today, 07:15 AM",
    prices: {
      Tomatoes: { headlinePrice: 30.0, minPrice: 26, maxPrice: 33, arrivalsTonnes: 85, netEstimatedPrice: 24.2 },
      Onions: { headlinePrice: 26.0, minPrice: 22, maxPrice: 29, arrivalsTonnes: 210, netEstimatedPrice: 22.1 },
      Potatoes: { headlinePrice: 19.0, minPrice: 16, maxPrice: 21, arrivalsTonnes: 100, netEstimatedPrice: 15.2 },
      Soybeans: { headlinePrice: 48.5, minPrice: 44, maxPrice: 52, arrivalsTonnes: 140, netEstimatedPrice: 43.2 },
      Wheat: { headlinePrice: 25.0, minPrice: 22, maxPrice: 27, arrivalsTonnes: 220, netEstimatedPrice: 21.4 },
      Cotton: { headlinePrice: 62.0, minPrice: 58, maxPrice: 66, arrivalsTonnes: 120, netEstimatedPrice: 55.6 },
    },
  },
  {
    id: "jalna-mandi",
    name: "Jalna APMC Market",
    nameHi: "जालना एपीएमसी बाजार",
    nameMr: "जालना एपीएमसी बाजार",
    district: "Jalna",
    districtHi: "जालना",
    districtMr: "जालना",
    lat: 19.8410,
    lng: 75.8864,
    distanceFromPuneKm: 280,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:55 AM",
    prices: {
      Tomatoes: { headlinePrice: 28.5, minPrice: 24, maxPrice: 31, arrivalsTonnes: 55, netEstimatedPrice: 22.8 },
      Onions: { headlinePrice: 25.0, minPrice: 21, maxPrice: 28, arrivalsTonnes: 160, netEstimatedPrice: 21.2 },
      Potatoes: { headlinePrice: 18.5, minPrice: 15, maxPrice: 20, arrivalsTonnes: 85, netEstimatedPrice: 14.8 },
      Soybeans: { headlinePrice: 49.5, minPrice: 45, maxPrice: 53, arrivalsTonnes: 170, netEstimatedPrice: 44.0 },
      Wheat: { headlinePrice: 25.5, minPrice: 23, maxPrice: 28, arrivalsTonnes: 200, netEstimatedPrice: 21.8 },
      Cotton: { headlinePrice: 63.0, minPrice: 59, maxPrice: 67, arrivalsTonnes: 130, netEstimatedPrice: 56.4 },
    },
  },
  {
    id: "latur-mandi",
    name: "Latur APMC Market",
    nameHi: "लातूर एपीएमसी बाजार",
    nameMr: "लातूर एपीएमसी बाजार",
    district: "Latur",
    districtHi: "लातूर",
    districtMr: "लातूर",
    lat: 18.4088,
    lng: 76.5604,
    distanceFromPuneKm: 300,
    congestionLevel: "Medium",
    verifiedDate: "Today, 06:40 AM",
    prices: {
      Tomatoes: { headlinePrice: 27.5, minPrice: 23, maxPrice: 30, arrivalsTonnes: 60, netEstimatedPrice: 22.0 },
      Onions: { headlinePrice: 24.5, minPrice: 20, maxPrice: 27, arrivalsTonnes: 150, netEstimatedPrice: 20.8 },
      Potatoes: { headlinePrice: 18.0, minPrice: 15, maxPrice: 20, arrivalsTonnes: 80, netEstimatedPrice: 14.4 },
      Soybeans: { headlinePrice: 50.0, minPrice: 46, maxPrice: 54, arrivalsTonnes: 190, netEstimatedPrice: 44.5 },
      Wheat: { headlinePrice: 26.0, minPrice: 23, maxPrice: 28, arrivalsTonnes: 230, netEstimatedPrice: 22.2 },
      Cotton: { headlinePrice: 64.0, minPrice: 60, maxPrice: 68, arrivalsTonnes: 140, netEstimatedPrice: 57.0 },
    },
  },
  {
    id: "nanded-mandi",
    name: "Nanded APMC Market",
    nameHi: "नांदेड़ एपीएमसी बाजार",
    nameMr: "नांदेड एपीएमसी बाजार",
    district: "Nanded",
    districtHi: "नांदेड़",
    districtMr: "नांदेड",
    lat: 19.1383,
    lng: 77.3210,
    distanceFromPuneKm: 360,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:20 AM",
    prices: {
      Tomatoes: { headlinePrice: 26.5, minPrice: 22, maxPrice: 29, arrivalsTonnes: 50, netEstimatedPrice: 21.2 },
      Onions: { headlinePrice: 23.5, minPrice: 19, maxPrice: 26, arrivalsTonnes: 130, netEstimatedPrice: 19.9 },
      Potatoes: { headlinePrice: 17.5, minPrice: 14, maxPrice: 19, arrivalsTonnes: 70, netEstimatedPrice: 14.0 },
      Soybeans: { headlinePrice: 49.5, minPrice: 45, maxPrice: 53, arrivalsTonnes: 160, netEstimatedPrice: 44.0 },
      Wheat: { headlinePrice: 25.5, minPrice: 23, maxPrice: 28, arrivalsTonnes: 210, netEstimatedPrice: 21.8 },
      Cotton: { headlinePrice: 63.5, minPrice: 59, maxPrice: 67, arrivalsTonnes: 120, netEstimatedPrice: 56.5 },
    },
  },
  {
    id: "parbhani-mandi",
    name: "Parbhani APMC Market",
    nameHi: "परभनी एपीएमसी बाजार",
    nameMr: "परभणी एपीएमसी बाजार",
    district: "Parbhani",
    districtHi: "परभनी",
    districtMr: "परभणी",
    lat: 19.2704,
    lng: 76.7748,
    distanceFromPuneKm: 320,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:25 AM",
    prices: {
      Tomatoes: { headlinePrice: 27.0, minPrice: 23, maxPrice: 30, arrivalsTonnes: 45, netEstimatedPrice: 21.6 },
      Onions: { headlinePrice: 24.0, minPrice: 20, maxPrice: 27, arrivalsTonnes: 120, netEstimatedPrice: 20.4 },
      Potatoes: { headlinePrice: 18.0, minPrice: 15, maxPrice: 20, arrivalsTonnes: 65, netEstimatedPrice: 14.4 },
      Soybeans: { headlinePrice: 50.5, minPrice: 46, maxPrice: 54, arrivalsTonnes: 180, netEstimatedPrice: 45.0 },
      Wheat: { headlinePrice: 26.0, minPrice: 23, maxPrice: 28, arrivalsTonnes: 220, netEstimatedPrice: 22.2 },
      Cotton: { headlinePrice: 64.5, minPrice: 60, maxPrice: 68, arrivalsTonnes: 135, netEstimatedPrice: 57.4 },
    },
  },
  {
    id: "beed-mandi",
    name: "Beed APMC Market",
    nameHi: "बीड एपीएमसी बाजार",
    nameMr: "बीड एपीएमसी बाजार",
    district: "Beed",
    districtHi: "बीड",
    districtMr: "बीड",
    lat: 18.9890,
    lng: 75.7601,
    distanceFromPuneKm: 260,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:50 AM",
    prices: {
      Tomatoes: { headlinePrice: 28.0, minPrice: 24, maxPrice: 31, arrivalsTonnes: 55, netEstimatedPrice: 22.4 },
      Onions: { headlinePrice: 25.5, minPrice: 21, maxPrice: 28, arrivalsTonnes: 140, netEstimatedPrice: 21.6 },
      Potatoes: { headlinePrice: 18.5, minPrice: 15, maxPrice: 20, arrivalsTonnes: 75, netEstimatedPrice: 14.8 },
      Soybeans: { headlinePrice: 49.0, minPrice: 45, maxPrice: 53, arrivalsTonnes: 160, netEstimatedPrice: 43.6 },
      Wheat: { headlinePrice: 25.5, minPrice: 23, maxPrice: 27, arrivalsTonnes: 190, netEstimatedPrice: 21.8 },
      Cotton: { headlinePrice: 63.0, minPrice: 59, maxPrice: 67, arrivalsTonnes: 125, netEstimatedPrice: 56.4 },
    },
  },

  // ─── Amravati / Vidarbha Division ───
  {
    id: "nagpur-mandi",
    name: "Nagpur APMC Market",
    nameHi: "नागपुर एपीएमसी बाजार",
    nameMr: "नागपूर एपीएमसी बाजार",
    district: "Nagpur",
    districtHi: "नागपुर",
    districtMr: "नागपूर",
    lat: 21.1458,
    lng: 79.0882,
    distanceFromPuneKm: 520,
    congestionLevel: "High",
    verifiedDate: "Today, 07:30 AM",
    prices: {
      Tomatoes: { headlinePrice: 31.0, minPrice: 27, maxPrice: 34, arrivalsTonnes: 110, netEstimatedPrice: 24.8 },
      Onions: { headlinePrice: 27.0, minPrice: 23, maxPrice: 30, arrivalsTonnes: 240, netEstimatedPrice: 23.0 },
      Potatoes: { headlinePrice: 20.0, minPrice: 17, maxPrice: 22, arrivalsTonnes: 150, netEstimatedPrice: 16.0 },
      Soybeans: { headlinePrice: 51.0, minPrice: 47, maxPrice: 55, arrivalsTonnes: 200, netEstimatedPrice: 45.4 },
      Wheat: { headlinePrice: 26.5, minPrice: 24, maxPrice: 29, arrivalsTonnes: 280, netEstimatedPrice: 22.6 },
      Cotton: { headlinePrice: 65.0, minPrice: 61, maxPrice: 69, arrivalsTonnes: 160, netEstimatedPrice: 57.8 },
    },
  },
  {
    id: "amravati-mandi",
    name: "Amravati APMC Market",
    nameHi: "अमरावती एपीएमसी बाजार",
    nameMr: "अमरावती एपीएमसी बाजार",
    district: "Amravati",
    districtHi: "अमरावती",
    districtMr: "अमरावती",
    lat: 20.9374,
    lng: 77.7796,
    distanceFromPuneKm: 450,
    congestionLevel: "Medium",
    verifiedDate: "Today, 07:00 AM",
    prices: {
      Tomatoes: { headlinePrice: 29.5, minPrice: 25, maxPrice: 32, arrivalsTonnes: 75, netEstimatedPrice: 23.6 },
      Onions: { headlinePrice: 26.0, minPrice: 22, maxPrice: 29, arrivalsTonnes: 180, netEstimatedPrice: 22.1 },
      Potatoes: { headlinePrice: 19.0, minPrice: 16, maxPrice: 21, arrivalsTonnes: 110, netEstimatedPrice: 15.2 },
      Soybeans: { headlinePrice: 50.5, minPrice: 46, maxPrice: 54, arrivalsTonnes: 220, netEstimatedPrice: 45.0 },
      Wheat: { headlinePrice: 26.0, minPrice: 23, maxPrice: 28, arrivalsTonnes: 250, netEstimatedPrice: 22.2 },
      Cotton: { headlinePrice: 64.5, minPrice: 60, maxPrice: 68, arrivalsTonnes: 170, netEstimatedPrice: 57.4 },
    },
  },
  {
    id: "akola-mandi",
    name: "Akola APMC Market",
    nameHi: "अकोला एपीएमसी बाजार",
    nameMr: "अकोला एपीएमसी बाजार",
    district: "Akola",
    districtHi: "अकोला",
    districtMr: "अकोला",
    lat: 20.7002,
    lng: 77.0082,
    distanceFromPuneKm: 420,
    congestionLevel: "Medium",
    verifiedDate: "Today, 06:45 AM",
    prices: {
      Tomatoes: { headlinePrice: 28.5, minPrice: 24, maxPrice: 31, arrivalsTonnes: 65, netEstimatedPrice: 22.8 },
      Onions: { headlinePrice: 25.0, minPrice: 21, maxPrice: 28, arrivalsTonnes: 160, netEstimatedPrice: 21.2 },
      Potatoes: { headlinePrice: 18.5, minPrice: 15, maxPrice: 20, arrivalsTonnes: 95, netEstimatedPrice: 14.8 },
      Soybeans: { headlinePrice: 51.5, minPrice: 47, maxPrice: 55, arrivalsTonnes: 230, netEstimatedPrice: 46.0 },
      Wheat: { headlinePrice: 26.5, minPrice: 24, maxPrice: 29, arrivalsTonnes: 240, netEstimatedPrice: 22.6 },
      Cotton: { headlinePrice: 65.5, minPrice: 61, maxPrice: 69, arrivalsTonnes: 180, netEstimatedPrice: 58.2 },
    },
  },
  {
    id: "yavatmal-mandi",
    name: "Yavatmal APMC Market",
    nameHi: "यवतमाल एपीएमसी बाजार",
    nameMr: "यवतमाळ एपीएमसी बाजार",
    district: "Yavatmal",
    districtHi: "यवतमाल",
    districtMr: "यवतमाळ",
    lat: 20.3880,
    lng: 78.1204,
    distanceFromPuneKm: 480,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:30 AM",
    prices: {
      Tomatoes: { headlinePrice: 27.5, minPrice: 23, maxPrice: 30, arrivalsTonnes: 55, netEstimatedPrice: 22.0 },
      Onions: { headlinePrice: 24.5, minPrice: 20, maxPrice: 27, arrivalsTonnes: 140, netEstimatedPrice: 20.8 },
      Potatoes: { headlinePrice: 18.0, minPrice: 15, maxPrice: 20, arrivalsTonnes: 85, netEstimatedPrice: 14.4 },
      Soybeans: { headlinePrice: 52.0, minPrice: 48, maxPrice: 56, arrivalsTonnes: 250, netEstimatedPrice: 46.5 },
      Wheat: { headlinePrice: 26.0, minPrice: 23, maxPrice: 28, arrivalsTonnes: 220, netEstimatedPrice: 22.2 },
      Cotton: { headlinePrice: 66.0, minPrice: 62, maxPrice: 70, arrivalsTonnes: 190, netEstimatedPrice: 58.6 },
    },
  },
  {
    id: "wardha-mandi",
    name: "Wardha APMC Market",
    nameHi: "वर्धा एपीएमसी बाजार",
    nameMr: "वर्धा एपीएमसी बाजार",
    district: "Wardha",
    districtHi: "वर्धा",
    districtMr: "वर्धा",
    lat: 20.7453,
    lng: 78.6022,
    distanceFromPuneKm: 500,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:35 AM",
    prices: {
      Tomatoes: { headlinePrice: 28.0, minPrice: 24, maxPrice: 31, arrivalsTonnes: 50, netEstimatedPrice: 22.4 },
      Onions: { headlinePrice: 25.0, minPrice: 21, maxPrice: 28, arrivalsTonnes: 130, netEstimatedPrice: 21.2 },
      Potatoes: { headlinePrice: 18.5, minPrice: 15, maxPrice: 20, arrivalsTonnes: 80, netEstimatedPrice: 14.8 },
      Soybeans: { headlinePrice: 51.0, minPrice: 47, maxPrice: 55, arrivalsTonnes: 210, netEstimatedPrice: 45.4 },
      Wheat: { headlinePrice: 26.5, minPrice: 24, maxPrice: 29, arrivalsTonnes: 240, netEstimatedPrice: 22.6 },
      Cotton: { headlinePrice: 65.0, minPrice: 61, maxPrice: 69, arrivalsTonnes: 170, netEstimatedPrice: 57.8 },
    },
  },
  {
    id: "chandrapur-mandi",
    name: "Chandrapur APMC Market",
    nameHi: "चंद्रपुर एपीएमसी बाजार",
    nameMr: "चंद्रपूर एपीएमसी बाजार",
    district: "Chandrapur",
    districtHi: "चंद्रपुर",
    districtMr: "चंद्रपूर",
    lat: 19.9615,
    lng: 79.2961,
    distanceFromPuneKm: 560,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:15 AM",
    prices: {
      Tomatoes: { headlinePrice: 27.0, minPrice: 23, maxPrice: 30, arrivalsTonnes: 45, netEstimatedPrice: 21.6 },
      Onions: { headlinePrice: 24.0, minPrice: 20, maxPrice: 27, arrivalsTonnes: 120, netEstimatedPrice: 20.4 },
      Potatoes: { headlinePrice: 17.5, minPrice: 14, maxPrice: 19, arrivalsTonnes: 75, netEstimatedPrice: 14.0 },
      Soybeans: { headlinePrice: 50.5, minPrice: 46, maxPrice: 54, arrivalsTonnes: 200, netEstimatedPrice: 45.0 },
      Wheat: { headlinePrice: 25.5, minPrice: 23, maxPrice: 28, arrivalsTonnes: 210, netEstimatedPrice: 21.8 },
      Cotton: { headlinePrice: 64.0, minPrice: 60, maxPrice: 68, arrivalsTonnes: 160, netEstimatedPrice: 57.0 },
    },
  },
  {
    id: "buldhana-mandi",
    name: "Buldhana APMC Market",
    nameHi: "बुलढाणा एपीएमसी बाजार",
    nameMr: "बुलढाणा एपीएमसी बाजार",
    district: "Buldhana",
    districtHi: "बुलढाणा",
    districtMr: "बुलढाणा",
    lat: 20.5292,
    lng: 76.1844,
    distanceFromPuneKm: 380,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:40 AM",
    prices: {
      Tomatoes: { headlinePrice: 28.0, minPrice: 24, maxPrice: 31, arrivalsTonnes: 50, netEstimatedPrice: 22.4 },
      Onions: { headlinePrice: 24.5, minPrice: 20, maxPrice: 27, arrivalsTonnes: 135, netEstimatedPrice: 20.8 },
      Potatoes: { headlinePrice: 18.0, minPrice: 15, maxPrice: 20, arrivalsTonnes: 80, netEstimatedPrice: 14.4 },
      Soybeans: { headlinePrice: 51.5, minPrice: 47, maxPrice: 55, arrivalsTonnes: 240, netEstimatedPrice: 46.0 },
      Wheat: { headlinePrice: 26.0, minPrice: 23, maxPrice: 28, arrivalsTonnes: 230, netEstimatedPrice: 22.2 },
      Cotton: { headlinePrice: 65.5, minPrice: 61, maxPrice: 69, arrivalsTonnes: 185, netEstimatedPrice: 58.2 },
    },
  },

  // ─── North Maharashtra / Khandesh ───
  {
    id: "jalgaon-mandi",
    name: "Jalgaon APMC Market",
    nameHi: "जलगांव एपीएमसी बाजार",
    nameMr: "जळगाव एपीएमसी बाजार",
    district: "Jalgaon",
    districtHi: "जलगांव",
    districtMr: "जळगाव",
    lat: 21.0077,
    lng: 75.5626,
    distanceFromPuneKm: 340,
    congestionLevel: "Medium",
    verifiedDate: "Today, 07:05 AM",
    prices: {
      Tomatoes: { headlinePrice: 30.0, minPrice: 26, maxPrice: 33, arrivalsTonnes: 70, netEstimatedPrice: 24.0 },
      Onions: { headlinePrice: 27.0, minPrice: 23, maxPrice: 30, arrivalsTonnes: 220, netEstimatedPrice: 23.0 },
      Potatoes: { headlinePrice: 19.5, minPrice: 16, maxPrice: 22, arrivalsTonnes: 100, netEstimatedPrice: 15.6 },
      Soybeans: { headlinePrice: 49.0, minPrice: 45, maxPrice: 53, arrivalsTonnes: 180, netEstimatedPrice: 43.6 },
      Wheat: { headlinePrice: 25.5, minPrice: 23, maxPrice: 28, arrivalsTonnes: 240, netEstimatedPrice: 21.8 },
      Cotton: { headlinePrice: 63.0, minPrice: 59, maxPrice: 67, arrivalsTonnes: 150, netEstimatedPrice: 56.4 },
    },
  },
  {
    id: "dhule-mandi",
    name: "Dhule APMC Market",
    nameHi: "धुले एपीएमसी बाजार",
    nameMr: "धुळे एपीएमसी बाजार",
    district: "Dhule",
    districtHi: "धुले",
    districtMr: "धुळे",
    lat: 20.9042,
    lng: 74.7749,
    distanceFromPuneKm: 300,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:55 AM",
    prices: {
      Tomatoes: { headlinePrice: 29.0, minPrice: 25, maxPrice: 32, arrivalsTonnes: 55, netEstimatedPrice: 23.2 },
      Onions: { headlinePrice: 26.0, minPrice: 22, maxPrice: 29, arrivalsTonnes: 170, netEstimatedPrice: 22.1 },
      Potatoes: { headlinePrice: 19.0, minPrice: 16, maxPrice: 21, arrivalsTonnes: 90, netEstimatedPrice: 15.2 },
      Soybeans: { headlinePrice: 48.5, minPrice: 44, maxPrice: 52, arrivalsTonnes: 150, netEstimatedPrice: 43.2 },
      Wheat: { headlinePrice: 25.0, minPrice: 22, maxPrice: 27, arrivalsTonnes: 200, netEstimatedPrice: 21.4 },
      Cotton: { headlinePrice: 62.0, minPrice: 58, maxPrice: 66, arrivalsTonnes: 130, netEstimatedPrice: 55.6 },
    },
  },
  {
    id: "nandurbar-mandi",
    name: "Nandurbar APMC Market",
    nameHi: "नंदुरबार एपीएमसी बाजार",
    nameMr: "नंदुरबार एपीएमसी बाजार",
    district: "Nandurbar",
    districtHi: "नंदुरबार",
    districtMr: "नंदुरबार",
    lat: 21.3669,
    lng: 74.2404,
    distanceFromPuneKm: 360,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:25 AM",
    prices: {
      Tomatoes: { headlinePrice: 28.0, minPrice: 24, maxPrice: 31, arrivalsTonnes: 40, netEstimatedPrice: 22.4 },
      Onions: { headlinePrice: 25.0, minPrice: 21, maxPrice: 28, arrivalsTonnes: 120, netEstimatedPrice: 21.2 },
      Potatoes: { headlinePrice: 18.5, minPrice: 15, maxPrice: 20, arrivalsTonnes: 70, netEstimatedPrice: 14.8 },
      Soybeans: { headlinePrice: 48.0, minPrice: 44, maxPrice: 52, arrivalsTonnes: 140, netEstimatedPrice: 42.8 },
      Wheat: { headlinePrice: 24.5, minPrice: 22, maxPrice: 26, arrivalsTonnes: 180, netEstimatedPrice: 21.0 },
      Cotton: { headlinePrice: 61.5, minPrice: 57, maxPrice: 65, arrivalsTonnes: 110, netEstimatedPrice: 55.0 },
    },
  },

  // ─── South Maharashtra / Western Ghats ───
  {
    id: "ratnagiri-mandi",
    name: "Ratnagiri APMC Market",
    nameHi: "रत्नागिरी एपीएमसी बाजार",
    nameMr: "रत्नागिरी एपीएमसी बाजार",
    district: "Ratnagiri",
    districtHi: "रत्नागिरी",
    districtMr: "रत्नागिरी",
    lat: 16.9902,
    lng: 73.3120,
    distanceFromPuneKm: 300,
    congestionLevel: "Low",
    verifiedDate: "Today, 07:10 AM",
    prices: {
      Tomatoes: { headlinePrice: 31.0, minPrice: 27, maxPrice: 34, arrivalsTonnes: 35, netEstimatedPrice: 25.2 },
      Onions: { headlinePrice: 26.0, minPrice: 22, maxPrice: 29, arrivalsTonnes: 70, netEstimatedPrice: 22.1 },
      Potatoes: { headlinePrice: 20.0, minPrice: 17, maxPrice: 22, arrivalsTonnes: 55, netEstimatedPrice: 16.0 },
      Soybeans: { headlinePrice: 46.0, minPrice: 42, maxPrice: 49, arrivalsTonnes: 30, netEstimatedPrice: 40.6 },
      Wheat: { headlinePrice: 25.0, minPrice: 22, maxPrice: 27, arrivalsTonnes: 80, netEstimatedPrice: 21.4 },
      Cotton: { headlinePrice: 59.0, minPrice: 55, maxPrice: 62, arrivalsTonnes: 20, netEstimatedPrice: 52.8 },
    },
  },
  {
    id: "sindhudurg-mandi",
    name: "Sindhudurg APMC Market",
    nameHi: "सिंधुदुर्ग एपीएमसी बाजार",
    nameMr: "सिंधुदुर्ग एपीएमसी बाजार",
    district: "Sindhudurg",
    districtHi: "सिंधुदुर्ग",
    districtMr: "सिंधुदुर्ग",
    lat: 16.0430,
    lng: 73.5270,
    distanceFromPuneKm: 380,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:50 AM",
    prices: {
      Tomatoes: { headlinePrice: 30.0, minPrice: 26, maxPrice: 33, arrivalsTonnes: 30, netEstimatedPrice: 24.4 },
      Onions: { headlinePrice: 25.5, minPrice: 21, maxPrice: 28, arrivalsTonnes: 60, netEstimatedPrice: 21.6 },
      Potatoes: { headlinePrice: 19.5, minPrice: 16, maxPrice: 22, arrivalsTonnes: 50, netEstimatedPrice: 15.6 },
      Soybeans: { headlinePrice: 45.5, minPrice: 41, maxPrice: 48, arrivalsTonnes: 25, netEstimatedPrice: 40.2 },
      Wheat: { headlinePrice: 24.5, minPrice: 22, maxPrice: 26, arrivalsTonnes: 70, netEstimatedPrice: 21.0 },
      Cotton: { headlinePrice: 58.5, minPrice: 54, maxPrice: 61, arrivalsTonnes: 18, netEstimatedPrice: 52.4 },
    },
  },
  {
    id: "osmanabad-mandi",
    name: "Dharashiv (Osmanabad) APMC",
    nameHi: "धाराशिव (उस्मानाबाद) एपीएमसी",
    nameMr: "धाराशिव (उस्मानाबाद) एपीएमसी",
    district: "Osmanabad",
    districtHi: "उस्मानाबाद",
    districtMr: "उस्मानाबाद",
    lat: 18.1860,
    lng: 76.0410,
    distanceFromPuneKm: 270,
    congestionLevel: "Low",
    verifiedDate: "Today, 06:45 AM",
    prices: {
      Tomatoes: { headlinePrice: 27.0, minPrice: 23, maxPrice: 30, arrivalsTonnes: 45, netEstimatedPrice: 21.6 },
      Onions: { headlinePrice: 24.0, minPrice: 20, maxPrice: 27, arrivalsTonnes: 110, netEstimatedPrice: 20.4 },
      Potatoes: { headlinePrice: 17.5, minPrice: 14, maxPrice: 19, arrivalsTonnes: 65, netEstimatedPrice: 14.0 },
      Soybeans: { headlinePrice: 49.5, minPrice: 45, maxPrice: 53, arrivalsTonnes: 170, netEstimatedPrice: 44.0 },
      Wheat: { headlinePrice: 25.5, minPrice: 23, maxPrice: 28, arrivalsTonnes: 200, netEstimatedPrice: 21.8 },
      Cotton: { headlinePrice: 63.5, minPrice: 59, maxPrice: 67, arrivalsTonnes: 115, netEstimatedPrice: 56.5 },
    },
  },
  {
    id: "ahmednagar-mandi",
    name: "Ahmednagar APMC Market",
    nameHi: "अहमदनगर एपीएमसी बाजार",
    nameMr: "अहमदनगर एपीएमसी बाजार",
    district: "Ahmednagar",
    districtHi: "अहमदनगर",
    districtMr: "अहमदनगर",
    lat: 19.0948,
    lng: 74.7480,
    distanceFromPuneKm: 120,
    congestionLevel: "Medium",
    verifiedDate: "Today, 07:20 AM",
    prices: {
      Tomatoes: { headlinePrice: 30.0, minPrice: 26, maxPrice: 33, arrivalsTonnes: 70, netEstimatedPrice: 24.2 },
      Onions: { headlinePrice: 25.5, minPrice: 21, maxPrice: 28, arrivalsTonnes: 150, netEstimatedPrice: 21.6 },
      Potatoes: { headlinePrice: 19.5, minPrice: 16, maxPrice: 22, arrivalsTonnes: 95, netEstimatedPrice: 15.6 },
      Soybeans: { headlinePrice: 47.5, minPrice: 43, maxPrice: 51, arrivalsTonnes: 110, netEstimatedPrice: 42.3 },
      Wheat: { headlinePrice: 25.0, minPrice: 22, maxPrice: 27, arrivalsTonnes: 200, netEstimatedPrice: 21.4 },
      Cotton: { headlinePrice: 61.0, minPrice: 57, maxPrice: 65, arrivalsTonnes: 100, netEstimatedPrice: 54.8 },
    },
  },
  {
    id: "shirdi-mandi",
    name: "Shirdi APMC Market",
    nameHi: "शिर्डी एपीएमसी बाजार",
    nameMr: "शिर्डी एपीएमसी बाजार",
    district: "Ahmednagar",
    districtHi: "अहमदनगर",
    districtMr: "अहमदनगर",
    lat: 19.7645,
    lng: 74.4762,
    distanceFromPuneKm: 190,
    congestionLevel: "Low",
    verifiedDate: "Today, 07:00 AM",
    prices: {
      Tomatoes: { headlinePrice: 29.0, minPrice: 25, maxPrice: 32, arrivalsTonnes: 50, netEstimatedPrice: 23.4 },
      Onions: { headlinePrice: 24.5, minPrice: 20, maxPrice: 27, arrivalsTonnes: 120, netEstimatedPrice: 20.8 },
      Potatoes: { headlinePrice: 18.5, minPrice: 15, maxPrice: 20, arrivalsTonnes: 75, netEstimatedPrice: 14.8 },
      Soybeans: { headlinePrice: 47.0, minPrice: 43, maxPrice: 50, arrivalsTonnes: 95, netEstimatedPrice: 41.8 },
      Wheat: { headlinePrice: 24.5, minPrice: 22, maxPrice: 26, arrivalsTonnes: 170, netEstimatedPrice: 21.0 },
      Cotton: { headlinePrice: 60.5, minPrice: 56, maxPrice: 64, arrivalsTonnes: 85, netEstimatedPrice: 54.4 },
    },
  },
];

// ─────────────────────────────────────────────────────────────
//  AUTO-ENRICH: Export crops for fallback data
//  Adds Mango / Grapes / Pomegranate / Banana / Orange to every
//  mandi with slight per-mandi price variation (±5%).
// ─────────────────────────────────────────────────────────────

const EXPORT_CROP_BASE = {
  Mango: { headlinePrice: 85.0, minPrice: 70, maxPrice: 100, arrivalsTonnes: 40, netEstimatedPrice: 79.9 },
  Grapes: { headlinePrice: 65.0, minPrice: 55, maxPrice: 75, arrivalsTonnes: 55, netEstimatedPrice: 61.1 },
  Pomegranate: { headlinePrice: 95.0, minPrice: 80, maxPrice: 110, arrivalsTonnes: 30, netEstimatedPrice: 89.3 },
  Banana: { headlinePrice: 30.0, minPrice: 25, maxPrice: 35, arrivalsTonnes: 80, netEstimatedPrice: 28.2 },
  Orange: { headlinePrice: 45.0, minPrice: 38, maxPrice: 52, arrivalsTonnes: 60, netEstimatedPrice: 42.3 },
};

MOCK_MANDIS.forEach((mandi) => {
  Object.entries(EXPORT_CROP_BASE).forEach(([crop, base]) => {
    if (!mandi.prices[crop]) {
      const variation = 0.95 + Math.random() * 0.10; // ±5%
      mandi.prices[crop] = {
        headlinePrice: +(base.headlinePrice * variation).toFixed(2),
        minPrice: +(base.minPrice * variation).toFixed(2),
        maxPrice: +(base.maxPrice * variation).toFixed(2),
        arrivalsTonnes: base.arrivalsTonnes,
        netEstimatedPrice: +(base.netEstimatedPrice * variation).toFixed(2),
      };
    }
  });
});

// ─────────────────────────────────────────────────────────────
//  Localization Helpers
// ─────────────────────────────────────────────────────────────

export function getMandiName(m: MandiMarket, lang: Language): string {
  if (lang === "hi") return m.nameHi;
  if (lang === "mr") return m.nameMr;
  return m.name;
}

export function getMandiDistrict(m: MandiMarket, lang: Language): string {
  if (lang === "hi") return m.districtHi;
  if (lang === "mr") return m.districtMr;
  return m.district;
}

export const CROP_LABELS: Record<string, { en: string; hi: string; mr: string }> = {
  Tomatoes: { en: "Tomatoes", hi: "टमाटर", mr: "टोमॅटो" },
  Onions: { en: "Red Onions", hi: "लाल प्याज", mr: "लाल कांदा" },
  Potatoes: { en: "Potatoes", hi: "आलू", mr: "बटाटा" },
  Soybeans: { en: "Soybeans", hi: "सोयाबीन", mr: "सोयाबीन" },
  Wheat: { en: "Wheat", hi: "गेहूं", mr: "गहू" },
  Cotton: { en: "Cotton", hi: "कपास", mr: "कापूस" },
  // 🆕 Export crops
  Mango: { en: "Mango", hi: "आम", mr: "आंबा" },
  Grapes: { en: "Grapes", hi: "अंगूर", mr: "द्राक्ष" },
  Pomegranate: { en: "Pomegranate", hi: "अनार", mr: "डाळिंब" },
  Banana: { en: "Banana", hi: "केला", mr: "केळी" },
  Orange: { en: "Orange", hi: "संतरा", mr: "संत्री" },
};

export function getCropLabel(cropId: string, lang: Language): string {
  return CROP_LABELS[cropId]?.[lang] ?? cropId;
}